# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Usuarioid', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apaterno', models.CharField(max_length=50)),
                ('Amaterno', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Passwd', models.CharField(max_length=20)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
    ]
