# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('EstudianteID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('aPaterno', models.CharField(max_length=30)),
                ('aMaterno', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=15)),
                ('Escuela', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
    ]

    
