# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('InstitucionID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('CoordenadaX', models.FloatField(null=True)),
                ('CoordenadaY', models.FloatField(null=True)),
            ],
        ),
    ]
